# Generated by Django 3.0.4 on 2020-09-22 18:51

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200920_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['top', 'left'], force_format=None, keep_meta=True, quality=0, size=[243, 136], upload_to='portfolio/img/'),
        ),
    ]
